services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "secret"
      MYSQL_TCP_PORT: 3306
      MYSQL_UNIX_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
