spring:
    application:
        name: recipe

    datasource:
        platform: mariadb
        driverClassName: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://${db.host}:${db.port}/recipe
        username: root
        password: secret

logging:
    level:
        com.jlogday.recipe: DEBUG
        org.springframework.jdbc.core.JdbcTemplate: DEBUG
